### ISSUE TITLE
AscendC and Newer Compilers

### ISSUE THREAD

**Issue by ThrudPrimrose** [ThrudPrimrose/AcceleratorCodeGen#4]
I will here describe the current issues with the DaCe AscendC code-gen (mainly supporting new C++ standards) and the Bisheng compiler.

**Comment by ThrudPrimrose** [comment]
I am working on the `atlas01` server.
System GCC is `gcc-7.50` installed through the apt package manager.
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

This version of `gcc` does not support `__thread_local` storage for the CPU available on the system if I use Bisheng and DaCe generated CMake file. `g++ -std=c++17 check_unix.cpp`

The compiler defines `__unix__` per my test.
```
#include <iostream>

int main() {
#ifdef __unix__
    std::cout << "__unix__ is defined!" << std::endl;
#else
    std::cout << "__unix__ is NOT defined!" << std::endl;
#endif
    return 0;
}
```

And `std::mutex` (which requires thread local storage) is also functional:
Compiled with `g++ -std=c++17 mut.cpp -pthread`
```
#include <iostream>
#include <thread>
#include <mutex>

const int NUM_THREADS = 4;
const int NUM_ITERATIONS = 1000;

int shared_value = 0;
std::mutex mtx;

void increment() {
    for (int i = 0; i < NUM_ITERATIONS; ++i) {
        std::lock_guard<std::mutex> lock(mtx);
        ++shared_value;
    }
}

int main() {
    std::thread threads[NUM_THREADS];
    for (int i = 0; i < NUM_THREADS; ++i) {
        threads[i] = std::thread(increment);
    }
    for (int i = 0; i < NUM_THREADS; ++i) {
        threads[i].join();
    }
    std::cout << "Final value: " << shared_value << std::endl;
    return 0;
}
```

DaCe can also generate CPU kernels and run them, for example:
```
import dace as dace
import numpy

N = dace.symbol('N', dtype=dace.int64)

@dace.program
def kernel(TSTEPS: dace.int64, A: dace.float64[N, N], B: dace.float64[N, N]):

    for t in range(1, TSTEPS):
        B[1:-1, 1:-1] = 0.2 * (A[1:-1, 1:-1] + A[1:-1, :-2] + A[1:-1, 2:] +
                               A[2:, 1:-1] + A[:-2, 1:-1])
        A[1:-1, 1:-1] = 0.2 * (B[1:-1, 1:-1] + B[1:-1, :-2] + B[1:-1, 2:] +
                               B[2:, 1:-1] + B[:-2, 1:-1])
    return A

_N = 1024
A = numpy.random.rand(_N, _N).astype(numpy.float64)
B = numpy.random.rand(_N, _N).astype(numpy.float64)

TSTEPS = 50
result = kernel(TSTEPS=TSTEPS, A=A, B=B, N=_N)

print(result)
```

This can run with:
```
git clone --recursive https://github.com/spcl/dace.git
cd dace
pip install -e .
cd ..
python dace_ex.py
```

**Comment by ThrudPrimrose** [comment]
So far everything is working.

I am using AscendC CANN toolkit 7.0.0 community edition.
Installed through these commands:
```
wget https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/CANN/CANN%207.0.0/Ascend-cann-toolkit_7.0.0_linux-x86_64.run
chmod +x ./Ascend-cann-toolkit_7.0.0_linux-x86_64.run
./Ascend-cann-toolkit_7.0.0_linux-x86_64.run --install-path=/scratch/ybudanaz/local --chip=Ascend910 --full --force
echo "source  /scratch1/ybudanaz/local/ascend-toolkit/set_env.sh" >> ~/.bashrc
```

I have also installed `gcc` version 13.2 using spack. I have installed `llvm-15` from a release. 
For llvm-15:
```
wget https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz
And I extracted the files to /scratch/ybudanaz/local.
This folder is included to the path.
```
For `gcc-13`:
```
git clone https://github.com/spack/spack.git ~/spack
echo ". share/spack/setup-env.sh" >> ~/.bashrc
exec bash
spack install gcc@13
```

Note, I add the `/scratch/ybudanaz/local` to all paths and include and link directories with:
```
export SCRATCH=/scratch1/ybudanaz

export PATH=$SCRATCH/local/bin:$PATH
export C_INCLUDE_PATH=$SCRATCH/local/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$SCRATCH/local/include:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$SCRATCH/local/lib64:$LD_LIBRARY_PATH
```

**Comment by learning-chip** [comment]
What is your starting point or "project template" for AscendC? Here are two lightweight examples [3_add_kernellaunch](https://gitee.com/ascend/samples/tree/8592035006032f5eba927ee8bc6fad17de126f35/operator/ascendc/0_introduction/3_add_kernellaunch/CppExtensions) and [13_matmulleakyrelu_kernellaunch](https://gitee.com/ascend/samples/tree/8592035006032f5eba927ee8bc6fad17de126f35/operator/ascendc/0_introduction/13_matmulleakyrelu_kernellaunch/CppExtensions) that are lighter than other samples or templates. Both only use pybind11 to connecting with pytorch NPU memory, and do not have too many cmake wrappers compared to other heavier examples.

**Comment by ThrudPrimrose** [comment]
I managed to have python bindings and compile an AscendC kernel, as well as call it from python.

I still do kot exactly know what triggered the thread local error, but in my solution essentially compile only for ONBOARD mode, enable the CCE language for all source files and ensure all headers and source files include a check on the ` __CCE_KT_TEST__` macro, I also need to explicitly link the `ascendcl` and `runtime` libraries to the stub/loader library then it complies.

Thanks for the information, I will check them if I have new issues.
