### ISSUE TITLE
Ascend Compiler

### ISSUE THREAD

**Issue by ThrudPrimrose** [ThrudPrimrose/AcceleratorCodeGen#7]
I have a question regarding the compile pipeline and which headers can be included in which files. I have compiled AscendC libraries and also loaded to python using ctypes. (The samples use pybind, I did not use it as DaCe loads libraries using ctypes)

To distinguish the files with AscendC kernels, I mark them with the extension `cce`, but I consider both file extensions (`cpp` and `cce`) with the language CCE to compile with `ccec`.

If I include specific headers from the standard library (<chrono>, <complex>, <numeric>, and many others), then I get various compile errors, but not if I include them in a `cpp` file.

For example one of the errors is:
```
In file included from /scratch/ybudanaz/AcceleratorCodeGen/GeneratedVectorAdd/vadd.cce:13:
/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/chrono:811:12: error: expected unqualified-id
    inline namespace _V2 {
```

I have tested with the installed `g++ 7.5`. Nested inline spaces are supported starting from `gcc 9` so this error is expected, but the interesting part is that this occurs only if included in a file with an AscendC kernel. Then I installed `gcc@13` using spack and used the `gcc@13` to compile `gcc@12` and ensured that the `gcc@12` is passed to the `ccec` such that this standard library is used but the error did not change:

```
In file included from /home/ybudanaz/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-13.2.0/gcc-12.3.0-fmxa5jdb4kukqtabjwxzhmtot33ej777/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../include/c++/12.3.0/chrono:39:
/home/ybudanaz/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-13.2.0/gcc-12.3.0-fmxa5jdb4kukqtabjwxzhmtot33ej777/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../include/c++/12.3.0/bits/chrono.h:1209:12: error: expected unqualified-id
    inline namespace _V2 {
    
 or for example:
 /home/ybudanaz/spack/opt/spack/linux-ubuntu18.04-cascadelake/gcc-13.2.0/gcc-12.3.0-fmxa5jdb4kukqtabjwxzhmtot33ej777/lib/gcc/x86_64-pc-linux-gnu/12.3.0/../../../../include/c++/12.3.0/bits/chrono.h:1463:35: error: no type named 'system_clock' in namespace 'std::chrono'
      using __sys_clock = chrono::system_clock;
                          ~~~~~~~~^
```

My question is, what headers can I use from files that have AscendC kernels? 
Not being able to include `<chrono>` and `<fstream>` prevents me from using the existing instrumentation functionality of DaCe on AscendC kernels, as DaCe currently generates instrumentation as part of the kernel (directly before and after it). 

Now I can do it if I put all kernels and their launchers (such that other files do not have `__global__` or `__aicore__` keyword) in a `.cce` file. Then, I can wrap the launcher with a second launcher and use all the standard library headers. Do you think this is how it should be done? Is this behaviour documented?

The `GeneratedVectorAdd` example in the repo you can use to inspect the latest code. On how I implemented the approach that circumvents this issue.

**Comment by learning-chip** [comment]
> My question is, what headers can I use from files that have AscendC kernels?
> Not being able to include `<chrono>` and `<fstream>` prevents me from using the existing instrumentation functionality of DaCe on AscendC kernels

Standard host-side C++ libraries cannot work inside Ascend kernels. Think it as a very naive version of nvcc that can only compile device-specific code and syntax.

To print inside an Ascend kernel, need to rely on custom tools like [msDebug to print memory state](https://www.hiascend.com/document/detail/zh/CANNCommunityEdition/800alpha002/devaids/opdev/optool/atlasopdev_16_0067.html)

**Comment by learning-chip** [comment]
> Then, I can wrap the launcher with a second launcher and use all the standard library headers.

the standard library headers

> Then, I can wrap the launcher with a second launcher and use all the standard library headers. Do you think this is how it should be done? Is this behaviour documented?

To actually hack a low-level kernel, you can refer to [this](https://github.com/deltaguo/haclv2/tree/master/hgemv) and [that](https://github.com/deltaguo/hablas/tree/master/src/kernel) projects.

However, to avoid too many debugging troubles, I still suggest following this [minimum official sample](https://gitee.com/ascend/samples/tree/master/operator/ascendc/0_introduction/3_add_kernellaunch/CppExtensions) of interfacing Ascend kernel and PyTorch, and keep the project template / cmake structure as-is.

**Comment by ThrudPrimrose** [comment]
Thanks for the pointer. I think I will continue on splitting the device code accordingly so that I can use dace features and still be able to compile kernels.

**Comment by ThrudPrimrose** [comment]
I think I can close the issue for now, the answers are quite clear, thanks for help

**Comment by learning-chip** [comment]
> keep the project template / cmake structure as-is.

There is a even [more minimum example](https://www.hiascend.com/document/detail/zh/canncommercial/80RC3/developmentguide/opdevg/BishengCompiler/atlas_bisheng_10_0002.html#ZH-CN_TOPIC_0000002045845628__zh-cn_topic_0000001856347698_section0667947112915) directly invoking `bisheng` (alias for `ccec`) on a single AscendC code file.
